# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc', '0002_auto_20180408_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image01',
            field=models.ImageField(blank=True, null=True, upload_to='fc/', verbose_name='Image'),
        ),
    ]
