# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171227_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_projectpagetag_items', to='taggit.Tag'),
        ),
    ]
