# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 21:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20171227_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
