# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectpage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
