# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_paleocoreoccurrencebaseclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleocoreoccurrencebaseclass',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='paleocoreoccurrencebaseclass',
            name='date_last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was last altered.', verbose_name='Modified'),
        ),
    ]
