# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0004_remove_site_mio_plio'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='origins',
            field=models.BooleanField(default=False),
        ),
    ]
