# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-23 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0005_context_origins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='mio_plio',
        ),
    ]
