# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0007_auto_20180107_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='last_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identificationqualifier',
            name='last_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxon',
            name='last_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxonrank',
            name='last_import',
            field=models.BooleanField(default=False),
        ),
    ]
