# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0008_auto_20180110_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
    ]
