# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0008_auto_20180110_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='fossil',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origins.Site'),
        ),
    ]
