# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0010_auto_20180330_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='alternate_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
