# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-07 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0011_site_alternate_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='fossil_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
