# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0012_site_fossil_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='default_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='descripition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
