# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0013_auto_20180412_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='descripition',
            new_name='description',
        ),
    ]
