# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-12 18:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0014_auto_20180412_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
