# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0017_auto_20180902_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='formation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='max_ma',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='min_ma',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
