# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/images/omo_mursi'),
        ),
    ]
