# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrp', '0008_auto_20180528_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='biology',
            name='attributes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biology',
            name='morphobank_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biology',
            name='preparations',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
