# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archaeology',
            options={'verbose_name': '02-MLP Archaeology', 'verbose_name_plural': '02-MLP Archaeology'},
        ),
        migrations.AlterModelOptions(
            name='biology',
            options={'verbose_name': '03-MLP Biology', 'verbose_name_plural': '03-MLP Biology'},
        ),
        migrations.AlterModelOptions(
            name='geology',
            options={'verbose_name': '04-MLP Geology', 'verbose_name_plural': '04-MLP Geology'},
        ),
        migrations.AlterModelOptions(
            name='identificationqualifier',
            options={'verbose_name': '07-MLP ID Qualifier'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'managed': True, 'verbose_name': '01-MLP Occurrence', 'verbose_name_plural': '01-MLP Occurrences'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'ordering': ['rank__ordinal', 'name'], 'verbose_name': '05-MLP Taxon', 'verbose_name_plural': '05-MLP Taxa'},
        ),
        migrations.AlterModelOptions(
            name='taxonrank',
            options={'verbose_name': '06-MLP Taxon Rank', 'verbose_name_plural': '06-MLP Taxon Ranks'},
        ),
        migrations.AlterField(
            model_name='biology',
            name='identified_by',
            field=models.CharField(blank=True, choices=[('Zeresenay Alemseged', 'Zeresenay Alemseged'), ('Yared Assefa', 'Yared Assefa'), ('Andrew Barr', 'Andrew Barr'), ('Rene Bobe', 'Rene Bobe'), ('Denis Geraads', 'Denis Geraads'), ('Tomas Getachew', 'Tomas Getachew'), ('Weldeyared Hailu', 'Waldeyared Hailu'), ('Shannon McPherron', 'Shannon McPherron'), ('Denne Reed', 'Denne Reed'), ('Peter Stamos', 'Peter Stamos'), ('Jonathan Wynn', 'Jonathan Wynn')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='collecting_method',
            field=models.CharField(choices=[('Surface Standard', 'Surface Standard'), ('Surface Intensive', 'Surface Intensive'), ('Surface Complete', 'Surface Complete'), ('Exploratory Survey', 'Exploratory Survey'), ('Dry Screen 5mm', 'Dry Screen 5mm'), ('Dry Screen 2mm', 'Dry Screen 2mm'), ('Wet Screen 1mm', 'Wet Screen 1mm'), ('Excavation', 'Excavation')], max_length=50, verbose_name='Collecting Method'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='collector',
            field=models.CharField(blank=True, choices=[('Zeresenay Alemseged', 'Zeresenay Alemseged'), ('Yared Assefa', 'Yared Assefa'), ('Andrew Barr', 'Andrew Barr'), ('Rene Bobe', 'Rene Bobe'), ('Denis Geraads', 'Denis Geraads'), ('Tomas Getachew', 'Tomas Getachew'), ('Weldeyared Hailu', 'Waldeyared Hailu'), ('Shannon McPherron', 'Shannon McPherron'), ('Denne Reed', 'Denne Reed'), ('Peter Stamos', 'Peter Stamos'), ('Jonathan Wynn', 'Jonathan Wynn')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='field_season',
            field=models.CharField(blank=True, choices=[('Jan 2014', 'Jan 2014'), ('Nov 2014', 'Nov 2014'), ('Nov 2015', 'Nov 2015'), ('Jan 2018', 'Jan 2018')], max_length=50, null=True),
        ),
    ]
