# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0003_auto_20180322_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biology',
            name='identified_by',
            field=models.CharField(blank=True, choices=[('Zeresenay Alemseged', 'Zeresenay Alemseged'), ('Yared Asseffa', 'Yared Assefa'), ('Andrew Barr', 'Andrew Barr'), ('Rene Bobe', 'Rene Bobe'), ('Denis Geraads', 'Denis Geraads'), ('Tomas Getachew', 'Tomas Getachew'), ('Waldeyared Hailu', 'Waldeyared Hailu'), ('Shannon McPherron', 'Shannon McPherron'), ('Denne Reed', 'Denne Reed'), ('Peter Stamos', 'Peter Stamos'), ('Jonathan Wynn', 'Jonathan Wynn')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='collector',
            field=models.CharField(blank=True, choices=[('Zeresenay Alemseged', 'Zeresenay Alemseged'), ('Yared Asseffa', 'Yared Assefa'), ('Andrew Barr', 'Andrew Barr'), ('Rene Bobe', 'Rene Bobe'), ('Denis Geraads', 'Denis Geraads'), ('Tomas Getachew', 'Tomas Getachew'), ('Waldeyared Hailu', 'Waldeyared Hailu'), ('Shannon McPherron', 'Shannon McPherron'), ('Denne Reed', 'Denne Reed'), ('Peter Stamos', 'Peter Stamos'), ('Jonathan Wynn', 'Jonathan Wynn')], max_length=50, null=True),
        ),
    ]
