# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 04:07
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0007_auto_20190315_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationqualifier',
            name='remarks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='General remarks about this database record.', max_length=500, null=True, verbose_name='Record Remarks'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='remarks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='General remarks about this database record.', max_length=500, null=True, verbose_name='Record Remarks'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='remarks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='General remarks about this database record.', max_length=500, null=True, verbose_name='Record Remarks'),
        ),
        migrations.AlterField(
            model_name='taxonrank',
            name='remarks',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='General remarks about this database record.', max_length=500, null=True, verbose_name='Record Remarks'),
        ),
    ]
