# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-31 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0009_auto_20190404_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='verbatim_kml_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
