# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20170105_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_page.html', 'Default Template'), ('pages/standard_page_full.html', 'Standard Page Full'), ('pages/paleocore_about_page.html', 'Paleocore About Page'), ('pages/paleocore_goals_page.html', 'Paleocore Goals Page'), ('pages/paleocore_projects_page.html', 'Paleocore Projects Page'), ('pages/paleocore_project_page.html', 'Paleocore Project Page'), ('pages/paleocore_workshops_page.html', 'Paleocore Workshops Page'), ('pages/paleocore_workshop_page.html', 'Paleocore Workshop Page'), ('pages/paleocore_tools_page.html', 'Paleocore Tools Page'), ('pages/paleocore_standards_page.html', 'Paleocore Standards Page'), ('pages/paleocore_help_page.html', 'Paleocore Help Page')], default='pages/standard_page.html', max_length=255),
        ),
    ]
