# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0002_auto_20180303_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='cm_specimen_number',
            new_name='cm_catalog_number',
        ),
    ]
