# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0004_auto_20180303_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificationqualifier',
            options={'verbose_name': 'GDB ID Qualifier'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'ordering': ['rank__ordinal', 'name'], 'verbose_name': 'GDB Taxon', 'verbose_name_plural': 'GDB Taxa'},
        ),
        migrations.AlterModelOptions(
            name='taxonrank',
            options={'verbose_name': 'GDB Taxon Rank', 'verbose_name_plural': 'GDB Taxon Ranks'},
        ),
        migrations.RenameField(
            model_name='biology',
            old_name='identification_qualifier',
            new_name='identification_qualifier_original',
        ),
        migrations.AddField(
            model_name='biology',
            name='taxon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='gdb_taxon_bio_occurrences', to='gdb.Taxon'),
        ),
    ]
