# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0005_auto_20180303_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='biology',
            name='identification_qualifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdb_id_qualifier_bio_occurrences', to='gdb.IdentificationQualifier'),
        ),
    ]
