# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0007_auto_20180315_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='collecting_method',
            field=models.CharField(blank=True, choices=[('Surface Standard', 'Prospecting'), ('Surface Intensive', 'Surface Crawl'), ('Dry Screen 2mm', 'Dry Screen 2mm')], max_length=50, null=True, verbose_name='Collecting Method'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Artifactual', 'Artifactual'), ('Faunal', 'Faunal'), ('Floral', 'Floral'), ('Geological', 'Geological'), ('Cast', 'Cast')], default='Faunal', max_length=255, null=True, verbose_name='Item Type'),
        ),
    ]
