# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-22 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdb', '0011_auto_20180822_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='sub_age',
            field=models.CharField(blank=True, choices=[('Cf1', 'Cf1'), ('Cf2', 'Cf2'), ('Cf3', 'Cf3'), ('Wa0', 'Wa0'), ('Wa1', 'Wa1'), ('Wa2', 'Wa2'), ('Wa3', 'Wa3'), ('Wa4', 'Wa4'), ('Wa5', 'Wa5'), ('Wa6', 'Wa6'), ('Wa7', 'Wa7'), ('Br0', 'Br0'), ('Br1a', 'Br1a'), ('Br1b', 'Br1b'), ('Br2', 'Br2'), ('Br3', 'Br3')], max_length=50, null=True),
        ),
    ]
