# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_project_projectterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('data_range', models.CharField(blank=True, max_length=255, null=True)),
                ('uses_controlled_vocabulary', models.BooleanField(default=False)),
                ('controlled_vocabulary', models.CharField(blank=True, max_length=75, null=True)),
                ('controlled_vocabulary_url', models.CharField(blank=True, max_length=155, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('is_class', models.BooleanField(default=False)),
                ('term_ordering', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=4000)),
                ('is_occurrence', models.BooleanField()),
                ('tree_visibility', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.TermCategory')),
            ],
            options={
                'verbose_name': 'Term Category',
                'verbose_name_plural': 'Term Categories',
                'db_table': 'standard_term_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name': 'Term Type',
                'verbose_name_plural': 'Term Types',
                'db_table': 'standard_term_data_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name': 'Term Status',
                'verbose_name_plural': 'Term Statuses',
                'db_table': 'standard_term_status',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='term',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.TermCategory'),
        ),
        migrations.AddField(
            model_name='term',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.TermDataType'),
        ),
        migrations.AddField(
            model_name='term',
            name='projects',
            field=models.ManyToManyField(blank=True, through='projects.ProjectTerm', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.TermStatus'),
        ),
        migrations.AddField(
            model_name='comment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.Term'),
        ),
    ]
