# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='paleocore_appname',
            field=models.CharField(choices=[('compressor', 'compressor'), ('taggit', 'taggit'), ('modelcluster', 'modelcluster'), ('wagtail.contrib.wagtailsitemaps', 'wagtail.contrib.wagtailsitemaps'), ('wagtail.contrib.wagtailsearchpromotions', 'wagtail.contrib.wagtailsearchpromotions'), ('wagtail.contrib.settings', 'wagtail.contrib.settings'), ('wagtail.wagtailforms', 'wagtail.wagtailforms'), ('wagtail.wagtailredirects', 'wagtail.wagtailredirects'), ('wagtail.wagtailembeds', 'wagtail.wagtailembeds'), ('wagtail.wagtailsites', 'wagtail.wagtailsites'), ('wagtail.wagtailusers', 'wagtail.wagtailusers'), ('wagtail.wagtailsnippets', 'wagtail.wagtailsnippets'), ('wagtail.wagtaildocs', 'wagtail.wagtaildocs'), ('wagtail.wagtailimages', 'wagtail.wagtailimages'), ('wagtail.wagtailsearch', 'wagtail.wagtailsearch'), ('wagtail.wagtailadmin', 'wagtail.wagtailadmin'), ('wagtail.wagtailcore', 'wagtail.wagtailcore'), ('wagtailfontawesome', 'wagtailfontawesome'), ('wagalytics', 'wagalytics'), ('cachalot', 'cachalot'), ('utils', 'utils'), ('pages', 'pages'), ('blog', 'blog'), ('events', 'events'), ('contact', 'contact'), ('people', 'people'), ('photo_gallery', 'photo_gallery'), ('products', 'products'), ('documents_gallery', 'documents_gallery'), ('account', 'account'), ('foundation_formtags', 'foundation_formtags'), ('wagtail_feeds', 'wagtail_feeds'), ('leaflet', 'leaflet'), ('djgeojson', 'djgeojson'), ('wagtailgeowidget', 'wagtailgeowidget'), ('mapwidgets', 'mapwidgets'), ('projects', 'projects'), ('cc', 'cc'), ('fc', 'fc'), ('gdb', 'gdb'), ('lgrp', 'lgrp'), ('mlp', 'mlp'), ('drp', 'drp'), ('hrp', 'hrp'), ('omo_mursi', 'omo_mursi'), ('origins', 'origins'), ('standard', 'standard')], max_length=200, null=True),
        ),
    ]
