# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_auto_20180503_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='namespace',
            field=models.CharField(blank=True, choices=[('cc', 'cc'), ('dc', 'dc'), ('drp', 'drp'), ('dwc', 'dwc'), ('fc', 'fc'), ('gdb', 'gdb'), ('hrp', 'hrp'), ('lgrp', 'lgrp'), ('mlp', 'mlp'), ('omo_mursi', 'omo_murse'), ('pc', 'pc')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.TermDataType'),
        ),
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.TermStatus'),
        ),
    ]
