# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_auto_20180528_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='term',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='term',
            name='is_vocabulary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='verbatim_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_verbatim_category', to='standard.TermCategory'),
        ),
        migrations.AlterField(
            model_name='term',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.TermCategory'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='term',
            name='namespace',
            field=models.CharField(blank=True, choices=[('cc', 'cc'), ('dc', 'dc'), ('drp', 'drp'), ('dwc', 'dwc'), ('fc', 'fc'), ('gdb', 'gdb'), ('hrp', 'hrp'), ('lgrp', 'lgrp'), ('mlp', 'mlp'), ('omo_mursi', 'omo_murse'), ('pc', 'pc'), ('rhoi', 'rhoi')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='termcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='termdatatype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='termstatus',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
