# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_auto_20180531_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uri', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='term',
            old_name='namespace',
            new_name='namespace_text',
        ),
    ]
