# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_auto_20180531_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
