# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_auto_20180531_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='namespace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.Namespace'),
        ),
    ]
