# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_auto_20180531_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.TermCategory'),
        ),
        migrations.AlterField(
            model_name='term',
            name='namespace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.Namespace'),
        ),
        migrations.AlterField(
            model_name='term',
            name='verbatim_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_verbatim_category', to='standard.TermCategory'),
        ),
    ]
