# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_auto_20180531_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='namespace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standard.Namespace'),
        ),
    ]
