# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-05 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_auto_20180605_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='namespace_abbreviation',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='namespace_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
