# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0014_auto_20180605_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='paleocore_appname',
            new_name='appname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_name',
        ),
    ]
