# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0015_auto_20180606_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='term',
            name='namespace_text',
        ),
        migrations.AddField(
            model_name='project',
            name='namespace_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Namespace',
        ),
    ]
