# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(blank=True, max_length=50, null=True)),
                ('element', models.CharField(blank=True, max_length=255, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
