# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioncode',
            options={'ordering': ['name'], 'verbose_name': '06-LGRP Collection Code'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': '05-LGRP Person', 'verbose_name_plural': '05-LGRP People'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'ordering': ['rank__ordinal', 'name'], 'verbose_name': '09-LGRP Taxon', 'verbose_name_plural': '09-LGRP Taxa'},
        ),
        migrations.AlterField(
            model_name='biology',
            name='identified_by',
            field=models.CharField(blank=True, choices=[('D. Braun', 'D. Braun'), ('J. Thompson', 'J. Thompson'), ('E. Scott', 'E. Scott'), ('E. Locke', 'E. Locke'), ('A.E. Shapiro', 'A.E. Shapiro'), ('A.W. Gentry', 'A.W. Gentry'), ('B.J. Schoville', 'B.J. Schoville'), ('B.M. Latimer', 'B.M. Latimer'), ('C. Denys', 'C. Denys'), ('C.A. Lockwood', 'C.A. Lockwood'), ('D. Geraads', 'D. Geraads'), ('D.C. Johanson', 'D.C. Johanson'), ('E. Delson', 'E. Delson'), ('B. Villmoare', 'B. Villmoare'), ('E.S. Vrba', 'E.S. Vrba'), ('F.C. Howell', 'F.C. Howell'), ('G. Petter', 'G. Petter'), ('G. Suwa', 'G. Suwa'), ('G.G. Eck', 'G.G. Eck'), ('H.B. Krentza', 'H.B. Krentza'), ('H.B. Wesselman', 'H.B. Wesselman'), ('H.B.S. Cooke', 'H.B.S. Cooke'), ('Institute Staff', 'Institute Staff'), ('J.C. Rage', 'J.C. Rage'), ('K.E. Reed', 'K.E. Reed'), ('L.A. Werdelin', 'L.A. Werdelin'), ('L.J. Flynn', 'L.J. Flynn'), ('M. Sabatier', 'M. Sabatier'), ('M.E. Lewis', 'M.E. Lewis'), ('N. Fessaha', 'N. Fessaha'), ('P. Brodkorb', 'P. Brodkorb'), ('R. Bobe-Quinteros', 'R. Bobe-Quinteros'), ('R. Geze', 'R. Geze'), ('R.L. Bernor', 'R.L. Bernor'), ('S.R. Frost', 'S.R. Frost'), ('T.D. White', 'T.D. White'), ('T.K. Nalley', 'T.K. Nalley'), ('V. Eisenmann', 'V. Eisenmann'), ('W.H. Kimbel', 'W.H. Kimbel'), ('Z. Alemseged', 'Z. Alemseged'), ('S. Oestmo', 'S. Oestmo'), ('J. Rowan', 'J. Rowan'), ('C.J. Campisano', 'C.J. Campisano'), ('J. Robinson', 'J. Robinson'), ('I. Smail', 'I. Smail'), ('I. Lazagabaster', 'I. Lazagabaster'), ('A. Rector', 'A. Rector')], max_length=100, null=True),
        ),
    ]
