# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_files', to='lgrp.Occurrence'),
        ),
        migrations.AlterField(
            model_name='image',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_images', to='lgrp.Occurrence'),
        ),
    ]
