# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lgrp', '0002_auto_20180108_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created')),
                ('date_last_modified', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was last altered.', verbose_name='Modified')),
                ('problem', models.BooleanField(default=False, help_text='Is there a problem with this record that needs attention?')),
                ('problem_comment', models.TextField(blank=True, help_text='Description of the problem.', max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, help_text='General remarks about this database record.', max_length=500, null=True, verbose_name='Record Remarks')),
                ('drainage_region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'LGRP Collection Code',
            },
        ),
        migrations.AlterModelOptions(
            name='identificationqualifier',
            options={'verbose_name': 'LGRP ID Qualifier'},
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='collection_code',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AM', 'AM'), ('AM12', 'AM12'), ('AS', 'AS'), ('AT', 'AT'), ('BD', 'BD'), ('BG', 'BG'), ('BR', 'BR'), ('DK', 'DK'), ('FD', 'FD'), ('GR', 'GR'), ('HD', 'HD'), ('HS', 'HS'), ('KG', 'KG'), ('KL', 'KL'), ('KT', 'KT'), ('LD', 'LD'), ('LG', 'LG'), ('LN', 'LN'), ('LS', 'LS'), ('MF', 'MF'), ('NL', 'NL'), ('OI', 'OI'), ('SS', 'SS')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='coll_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgrp.CollectionCode'),
        ),
    ]
