# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgrp', '0003_taxon_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationqualifier',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
    ]
