# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20180407_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image01',
            field=models.ImageField(blank=True, null=True, upload_to='cc/', verbose_name='Image'),
        ),
    ]
