# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20180408_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excavation_unit',
            new_name='ExcavationUnit',
        ),
    ]
