# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_auto_20180515_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='excavationunit',
            table='cc_excavation_unit',
        ),
    ]
