# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_auto_20180515_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Small_Find',
            new_name='SmallFind',
        ),
        migrations.DeleteModel(
            name='Lithics_with_Photos',
        ),
        migrations.CreateModel(
            name='LithicsWithPhotos',
            fields=[
            ],
            options={
                'verbose_name': 'cc Lithic (only with photo)',
                'verbose_name_plural': 'cc Lithics (only with photos)',
                'managed': True,
                'proxy': True,
                'indexes': [],
            },
            bases=('cc.context',),
        ),
        migrations.AlterModelTable(
            name='smallfind',
            table='cc_small_find',
        ),
    ]
