# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drp', '0002_auto_20180518_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonrank',
            options={'verbose_name': 'Taxon Rank', 'verbose_name_plural': 'Taxon Ranks'},
        ),
    ]
