# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-28 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drp', '0005_occurrence_field_number_orig'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='date_recorded',
            field=models.DateTimeField(blank=True, help_text='Date and time the item was observed or collected.', null=True, verbose_name='Date Rec'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='last_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='barcode',
            field=models.IntegerField(blank=True, help_text='For collected items only.', null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='field_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='year_collected',
            field=models.IntegerField(blank=True, help_text='The year, event or field campaign during which the item was found.', null=True, verbose_name='Year'),
        ),
    ]
